import './globals.css'
import { Inter } from 'next/font/google'
import Head from "./head";
//Autre façon de gérer les métadatas:
import type {Metadata} from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
